config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:index, :new, :create,:destroy] do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resources :comments, only: [:create]
      collection do
        get 'search'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post



  with_options presence: true do
    validates :text
    validates :user_id
    validates :room_id
    validates :post_id

  end
end

app/models/event.rb
class Event < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '出産' },
    { id: 3, name: '誕生日' },
    { id: 4, name: 'お七夜' },
    { id: 5, name: 'お宮参り' },
    { id: 6, name: 'お食い初め' },
    { id: 7, name: '初正月' },
    { id: 8, name: '初節分' },
    { id: 9, name: '桃の節句' },
    { id: 10, name: '端午の節句' },
    { id: 11, name: 'ハーフバースデー' },
    { id: 12, name: 'その他' }
  ]
include ActiveHash::Associations
has_many :posts
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
   { id: 1, name: '--' },
   { id: 2, name: '女の子' },
   { id: 3, name: '男の子' },
 ]
 include ActiveHash::Associations
 has_many :rooms
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :event
  belongs_to :room
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :room_id
    validates :user_id
    validates :image
  end
end

app/models/room.rb
class Room < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_one_attached :image
  has_many :comments
  has_many :posts, dependent: :destroy
  
  validates :gender_id, numericality: { other_than: 1 } 


  with_options presence: true do
    validates :babyname
    validates :gender_id
    validates :user_id
    validates :birthday
    validates :image
  end
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :posts
  has_many :comments
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.new(comment_params)
    comment.save
    redirect_to room_post_path(params[:room_id], params[:post_id],)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(room_id: params[:room_id], post_id: params[:post_id], user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :unmatched_user_redirect_root_path

  def index
    @posts = Post.includes(:room)
    @birthday = Date.parse("#{@room.birthday.to_s}")

    @shooting_dates = []
    event_ids = [1]
    @posts.each do |post|
      if @room.id == post.room_id
        @shooting_dates << [Date.parse("#{post.shooting_date.to_s}")]
        event_ids << post.event_id
      end
    end
    @event = Event.find(event_ids.uniq)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)

  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to room_posts_path(params[:room_id])
  end

  def post_search
    @posts = Post.includes(:room)
    @birthday = Date.parse("#{@room.birthday.to_s}")

    @shooting_dates = []
    @posts.each do |post|
      if @room.id == post.room_id
        @shooting_dates << [Date.parse("#{post.shooting_date.to_s}")]
      end
    end

    render json: {post_shooting_date: @shooting_dates}
  end

  private
  def post_params
    room = Room.find(params[:room_id])
    params.require(:post).permit(:shooting_date, :event_id, :image).merge(room_id: room.id, user_id: current_user.id )
  end

  def unmatched_user_redirect_root_path
    @room = Room.find(params[:room_id])
    @room_users = RoomUser.where(id: @room.room_users.ids)
    room_user_id = []
    @room_users.each do |room_user|
      room_user_id << room_user.user.id
    end
    unless room_user_id.include?(current_user.id)
      redirect_to root_path
    end
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room_users = RoomUser.where(id: room.room_users.ids)
    room_users.each do |room_user|
      room_user.destroy
    end
    room.destroy
    redirect_to root_path
  end

  private
  def room_params
    params.require(:room).permit(:babyname, :gender_id, :birthday, :image, user_ids: []).merge(user_id: current_user.id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
  end

  def update
    if current_user.update(user_params)
      sign_in(current_user, :bypass => true)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Babylog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel = "stylesheet" type = "text / css" href = "http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css" > 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render "shared/header" %>

<div class="post_index">
  <div class="post">
    <%= link_to "写真を投稿する", new_room_post_path, class: "post_btn" %>
  </div>

  <div class="room_member">
  ルームメンバー：
    <% @room_users.each do |room_user| %>
        <%= User.find(room_user.user_id).nickname %>さん
    <% end %>
    
  </div>

  <%= form_with model: @post, url: search_room_posts_path(@room), method: :get, id: "search_form", local: true do |f| %>
    <div class="search_field">
      <div class="date">
        <p>日付を選択</p>
        <%= f.select :shooting_date, @shooting_dates.uniq, include_blank: "--", class: "shooting_dates"%>
      </div>
      <div>
        <p>イベントを選択</p>
        <%= f.collection_select(:event_id, @event, :id, :name, {})%>
      </div>
    </div>
  <% end %>
  <button id="all_show_btn">全て表示</button>

  <P class="album" id="album"> <%= @room.babyname %>のアルバム </p>

  <%@posts.each do |post|%>
    <%if @room.id == post.room_id%>
      <div class="post-images <%=post.shooting_date%> <%=post.event_id%>" shooting-date=<%= post.shooting_date%> id=<%= post.id%>>
        <%= link_to room_post_path(@room.id, post.id) do%>
          <%=image_tag post.image.variant(resize: '300x200'),class: "image"%>
        <% end %>
      </div>
    <% end %> 
  <%end%> 
  <% if current_user.id == @room.user_id%>
    <div class="room_delete">
      <%= link_to "このアルバムを削除する", room_path(@room), method: :delete, class: "room_delete" %>
    </div>
  <%end%>
</div>
<div class="back">
  <%= link_to "＜戻る", root_path, class: "back"%>
</div>

app/views/posts/new.html.erb
<%= render "shared/header" %>

<div class= "create_post">
<%= form_with model: [@room,@post], local: true do |f|%>

<%= render 'shared/error_messages', model: f.object %>

  <div class="create_post_field">
      <p>写真をアップロード</p>
      <%= f.file_field :image, id:"item-image" %>
  </div>

  <div class="input-birth-wrap create_post_field">
    <%= f.label :撮影日 %>
     <%= raw sprintf(
                  f.date_select(
                    :shooting_date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 2000,
                    end_year: (Time.now.year),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
  </div>

   <div class="create_post_field">
    <%= f.label :イベント %>
    <%= f.collection_select(:event_id, Event.all, :id, :name, {})%>
  </div>
  
  <div class="create_post_submit">
    <%= f.submit "投稿する", class: "create_post_btn" %>
  </div>
<% end %>
</div>

<div class="back">
  <%= link_to "＜戻る", :back, class: "back"%> 
</div>

app/views/posts/show.html.erb
<%= render "shared/header" %>

<div class="post_show">
  <%= image_tag @post.image.variant(resize: '350x350') %>

<div class="shooting_date">
  <%= @post.shooting_date%>
</div>


  <div>
    <% if user_signed_in? %>
      <%= form_with(model: [@room, @post, @comment], local: true) do |f| %>
        <%= f.text_area :text, placeholder: "感想", rows: "3", class: "comment_area" %><br>
        <%= f.submit "コメントする", class: "comment_btn" %>
      <% end %>
    <% else %>
          <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
  </div>

  <div>
    <% @comments.each do |comment| %>
      <p class="comment_text">
        <strong class="comment_user"><%= comment.user.nickname %>：</strong>
        <%= comment.text %>
      </p>
    <% end %>
  </div>
  <div class="post_delete">
    <% if current_user.id == @post.user_id %>
      <%= link_to "投稿を削除する", room_post_path(@room, @post), class: "post_delete_btn", method: :delete %>
    <% end %>
  </div>
</div>


<div class="back">
  <%= link_to "＜戻る", :back, class: "back"%> 
</div>

app/views/rooms/index.html.erb
<%if user_signed_in?%>
  <%= render "shared/header" %>
  <p class="album_choice">アルバム</p>
  <div class="room_image">
    <%current_user.rooms.each do |room|%>
      <%= link_to room_posts_path(room.id) do%>
        <div class="room">
          <%=room.babyname%>
          <%if room.image.attached?%>
            <div>
              <%= image_tag room.image.variant(resize: '100x100')%>
            </div>
          <%end%>
        </div>
      <%end%>
    <%end%>
  </div>
  <div class="create_room">
    <%= link_to "アルバムを作る", new_room_path, class: "create_room_btn" %>
  </div>
<%else%>
  <div class="first-top-page">
      <p>
        <%= link_to "BabyLog", root_path, class: "title" %>
      </p>
      <ul class="first-top-page-list">
        <li class="first-top-page-sign_up"><%= link_to "新規登録", new_user_registration_path, class: "sign_up" %></li>
        <li class="first-top-page-login"><%= link_to "ログイン", new_user_session_path, class: "login" %></li>
      </ul>
  </div>
<%end%>

app/views/rooms/new.html.erb
<%= render "shared/header" %>

<div class="room_create">
  <%= form_with model: @room, local: true do |f|%>

  <%= render 'shared/error_messages', model: f.object %>
  
    <div class="create_room_field">
      <%= f.label :お子様のお名前 %>
      <%= f.text_field :babyname, placeholder: 'お子様のお名前'%>
    </div>

    <div class="create_room_field">
      <%= f.label :性別 %>
      <%= f.collection_select(:gender_id, Gender.all, :id, :name, {})%>
    </div>

    <div class="input-birth-wrap create_room_field">
      <%= f.label :生年月日 %>
      <%= raw sprintf(
                    f.date_select(
                      :birthday,
                      class:'select-birth',
                      id:"birth-date",
                      use_month_numbers: true,
                      prompt:'--',
                      start_year: 2000,
                      end_year: (Time.now.year),
                      date_separator: '%s'),
                    "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <div class="create_room_field">
        <p>写真をアップロード</p>
        <%= f.file_field :image, id:"item-image" %>
    </div>

    <div class="create_room_field">ルームに入れるユーザーを選択</div>
      <select name="room[user_ids][]" multiple>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.nickname %></option>
          <% end %>
      </select>
    <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
    <div class="create_room_submit">
      <%= f.submit "アルバムを作成する", class: "create_room_btn"%>
    </div>
  <% end %>
</div>
  <div class="back">
    <%= link_to "＜戻る", root_path, class: "back"%>
  </div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="header_title">
    <%= link_to "BabyLog", root_path, class: "header_title" %>
  </div>

  <ul class="user_info">
    <% if signed_in? %>
      <li><%= link_to current_user.nickname, edit_user_path(current_user), class: "user_name" %></li>
      <li><%= link_to "ログアウト", destroy_user_session_path, class: "log_out", method: :delete %></li>
    <%end%>
</ul>
</header>

app/views/users/edit.html.erb
<%= render "shared/header" %>

<h2>アカウントの編集</h2>

<%= form_with model: current_user, class: 'edit-main', local: true do |f|%>
  <%# <%= render "devise/shared/error_messages", resource: resource%>

  <div class="field">
    <%= f.label :名前 %><br />
    <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname", class: "nickname_field"%>
  </div>
  
  <div class="field">
    <%= f.label :メールアドレス %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email",class: "mail_field" %>
  </div>


  <div class="field">
    <%= f.label :変更後のパスワード %> <i></i><br />
    <%= f.password_field :password, autocomplete: "new-password", class: "password_field" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> </em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :変更後のパスワード確認 %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "password_field" %>
  </div>

  <div class="field">
    <%= f.label :変更前のパスワード %> <i></i><br />
    <%= f.password_field :current_password, autocomplete: "current-password", class: "password_field" %>
  </div>

  <div class="actions">
    <%= f.submit "変更", class: "update_submit" %>
  </div>
<% end %>




<div class="back">
  <%= link_to "＜戻る", root_path, class: "back"%>
</div>